version: "3.9"
services:

    admin:
        build:
            context: .
            dockerfile: Admin/Dockerfile
        image: "admin"
        networks:
            - microservices

    afazer:
        build:
            context: .
            dockerfile: afazer/Dockerfile
        environment:
            ADMIN_HOST: admin
        image: "afazer"
        networks:
            - microservices
        ports:
            - "5000:5000"

networks:
    microservices: