version: "3.9"
services:

    database_usuarios:
        container_name: usuarios
        image: "postgres:latest"
        env_file: database_usuarios.conf
        ports:
            - "5432:5432"
        networks:
            microservices:
        volumes:
            - db_volume_usuarios:/var/lib/postgresql

networks:
    microservices:
volumes:
    db_volume_usuarios: