version: "3.9"
services:

    database_usuarios:
        container_name: usuarios
        image: "postgres:latest"
        env_file: database_usuarios.conf
        ports:
            - "5432:5432"
        networks:
            microservices:
        volumes:
            - db_volume_usuarios:/var/lib/postgresql
    database_atividades:
        container_name: atividades
        image: "postgres:latest"
        env_file: database_atividades.conf
        ports:
            - "5433:5432"
        networks:
            microservices:
        volumes:
            - db_volume_atividades:/var/lib/postgresql
    proxy:
        container_name: nginx
        image: nginx:1.19.10-alpine
        ports:
            - 8081:80
            - 443:443
        volumes:
            - ./proxy/conf/nginx.conf:/etc/nginx/nginx.conf
            - ./proxy/certificados:/etc/nginx/certs
        depends_on:
            - afazer
        restart: on-failure
        networks:
            - microservices
    admin:
        container_name: admin
        build:
            context: .
            dockerfile: Admin/Dockerfile
        depends_on:
            -   database_usuarios
        restart: on-failure
        image: "admin"
        env_file: database_usuarios.conf
        networks:
            - microservices
        ports:
            - "5001:5001"
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 3000M

    servidor_usuarios:
        container_name: servidor_usuarios
        build:
            context: .
            dockerfile: servidor_usuarios/Dockerfile
        depends_on:
            - database_usuarios
        restart: on-failure
        image: "servidor_usuarios"
        env_file: database_usuarios.conf
        networks:
            - microservices
        ports:
            -   "50051:50051"
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 3000M
    afazer:
        container_name: afazer
        build:
            context: .
            dockerfile: afazer/Dockerfile
        env_file: database_atividades.conf
        environment:
            ADMIN_HOST: servidor_usuarios
        depends_on:
            -   database_atividades
        restart: on-failure
        image: "afazer"
        networks:
            - microservices
        ports:
            - "8080:80"
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 3000M


networks:
    microservices:
volumes:
    db_volume_usuarios:
    db_volume_atividades: