# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: usuarios.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='usuarios.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eusuarios.proto\"4\n\nRequisicao\x12\x17\n\x06\x63oluna\x18\x01 \x01(\x0e\x32\x07.Coluna\x12\r\n\x05valor\x18\x02 \x01(\t\"T\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\r\n\x05login\x18\x03 \x01(\t\x12\r\n\x05senha\x18\x04 \x01(\t\x12\x14\n\x0ctipo_usuario\x18\x05 \x01(\t\"#\n\x08Resposta\x12\x17\n\x08usuarios\x18\x01 \x03(\x0b\x32\x05.User*B\n\x06\x43oluna\x12\x06\n\x02ID\x10\x00\x12\x08\n\x04NOME\x10\x01\x12\t\n\x05LOGIN\x10\x02\x12\t\n\x05SENHA\x10\x03\x12\x10\n\x0cTIPO_USUARIO\x10\x04\x32\x36\n\x08Usuarios\x12*\n\x10RetornarUsuarios\x12\x0b.Requisicao\x1a\t.Respostab\x06proto3'
)

_COLUNA = _descriptor.EnumDescriptor(
  name='Coluna',
  full_name='Coluna',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NOME', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOGIN', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SENHA', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TIPO_USUARIO', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=195,
  serialized_end=261,
)
_sym_db.RegisterEnumDescriptor(_COLUNA)

Coluna = enum_type_wrapper.EnumTypeWrapper(_COLUNA)
ID = 0
NOME = 1
LOGIN = 2
SENHA = 3
TIPO_USUARIO = 4



_REQUISICAO = _descriptor.Descriptor(
  name='Requisicao',
  full_name='Requisicao',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='coluna', full_name='Requisicao.coluna', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='valor', full_name='Requisicao.valor', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=70,
)


_USER = _descriptor.Descriptor(
  name='User',
  full_name='User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='User.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nome', full_name='User.nome', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='login', full_name='User.login', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='senha', full_name='User.senha', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tipo_usuario', full_name='User.tipo_usuario', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=156,
)


_RESPOSTA = _descriptor.Descriptor(
  name='Resposta',
  full_name='Resposta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='usuarios', full_name='Resposta.usuarios', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=193,
)

_REQUISICAO.fields_by_name['coluna'].enum_type = _COLUNA
_RESPOSTA.fields_by_name['usuarios'].message_type = _USER
DESCRIPTOR.message_types_by_name['Requisicao'] = _REQUISICAO
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['Resposta'] = _RESPOSTA
DESCRIPTOR.enum_types_by_name['Coluna'] = _COLUNA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Requisicao = _reflection.GeneratedProtocolMessageType('Requisicao', (_message.Message,), {
  'DESCRIPTOR' : _REQUISICAO,
  '__module__' : 'usuarios_pb2'
  # @@protoc_insertion_point(class_scope:Requisicao)
  })
_sym_db.RegisterMessage(Requisicao)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'usuarios_pb2'
  # @@protoc_insertion_point(class_scope:User)
  })
_sym_db.RegisterMessage(User)

Resposta = _reflection.GeneratedProtocolMessageType('Resposta', (_message.Message,), {
  'DESCRIPTOR' : _RESPOSTA,
  '__module__' : 'usuarios_pb2'
  # @@protoc_insertion_point(class_scope:Resposta)
  })
_sym_db.RegisterMessage(Resposta)



_USUARIOS = _descriptor.ServiceDescriptor(
  name='Usuarios',
  full_name='Usuarios',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=263,
  serialized_end=317,
  methods=[
  _descriptor.MethodDescriptor(
    name='RetornarUsuarios',
    full_name='Usuarios.RetornarUsuarios',
    index=0,
    containing_service=None,
    input_type=_REQUISICAO,
    output_type=_RESPOSTA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_USUARIOS)

DESCRIPTOR.services_by_name['Usuarios'] = _USUARIOS

# @@protoc_insertion_point(module_scope)
